server:
  port: 9000

spring:
  application:
    name: Zuul

#para ignorar serviços
#zuul:
#  ignoredServices: '*'

zuul:
  routes:
    cliente:
      path: /cliente/**
      serviceId: cliente
      stripPrefix: false
    cartao:
      path: /cartao/**
      serviceId: cartao
      stripPrefix: false
    cep:
      path: /cep/**
      url: https://viacep.com.br/ws/
